import type { Metadata } from "next";
import { locales } from "../../lib/config";
// import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-AppRouter";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Create Next App",
  },
  description: "Generated by create next app",
  keywords: ["Next.js", "React", "JavaScript"],
  generator: "Next.js",
  applicationName: "Next.js",
  referrer: "origin-when-cross-origin",
  authors: [{ name: "Seb" }, { name: "Josh", url: "https://nextjs.org" }],
  creator: "Jiachi Liu",
  publisher: "Sebastian Markbåge",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL("http://localhost:3001"),
  alternates: {
    canonical: "/",
    languages: {
      zh: "/zh",
      en: "/en",
    },
  },
  openGraph: {
    images: "/og-image.png",
  },
};

export async function generateStaticParams() {
  return locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <body className="mx-20">
        <Header />
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
      </body>
    </html>
  );
}
